eureka:
  client:
    enabled: false
server:
  port: 7000
spring:
  application:
    name: document-generation-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  datasource:
    url: jdbc:mysql://5.200.47.32:3306/arsenal?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Kiev
    username: sergey
    password: vAlAvin2002
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
